"""
Django settings for mse project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

from unipath import Path
import json
from django.core.exceptions import ImproperlyConfigured

# 3-tier approach Using Unipath per Two Scoops
BASE_DIR = Path(__file__).ancestor(3)

# JSON-based secrets module
with open(BASE_DIR.child('mse', 'settings', 'secrets.json')) as f:
    secrets = json.loads(f.read())

def get_secret(setting, secrets=secrets):
    """ Get the secret variable or return explicit exception. """
    try:
        return secrets[setting]
    except KeyError:
        error_msg = "Set the {0} environment variable".format(setting)
        raise ImproperlyConfigured(error_msg)

SECRET_KEY = get_secret("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'msedb',
        'USER': 'msedb_user',
        'PASSWORD': 'cwmorgan$1814',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    },
    'msemap_db': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'msemap_db',
        'USER': 'msemap_user',
        'PASSWORD': 'FranAllen$1891',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Application definition

INSTALLED_APPS = (
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'about.apps.AboutConfig',
    'artifacts.apps.ArtifactsConfig',
    'community.apps.CommunityConfig',
    'connections.apps.ConnectionsConfig',
    'core.apps.CoreConfig',
    'curriculum.apps.CurriculumConfig',
    'documents.apps.DocumentsConfig',
    'mapdata.apps.MapdataConfig',
    'maps.apps.MapsConfig',
    'resources.apps.ResourcesConfig',
    'scholars.apps.ScholarsConfig',
    'sitewide.apps.SitewideConfig',
    'videos.apps.VideosConfig',
    #'tinymce',     
)

# Second database for map data
DATABASE_ROUTERS = ['mse.routers.MapdataRouter',]

# MIDDLEWARE_CLASSES = (
MIDDLEWARE = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'mse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.child("templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mse.wsgi.application'


# Database connections defined in inheriting settings files


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_URL = '/static/'

# Static files (CSS, JavaScript, Images)
STATIC_ROOT = BASE_DIR.ancestor(2).child("mse_static")

STATICFILES_DIRS = (
    BASE_DIR.child("local_static"),
)

SITE_ID = 1

# 3 for devel, 4 for public
STATUS_LEVEL = 4
# for devel vs. produciton diffes: google analytics in base.html
IS_PRODUCTION = False

# For Django 3.2
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
