# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='anchor_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='barrel_yield',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='barrels_other_oil',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='barrels_sperm_breakdown',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='voyage',
            name='barrels_sperm_oil',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='barrels_train_oil',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='bib_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='boats_lowered',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='voyage',
            name='code_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='dayofweek',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='voyage',
            name='days_at_sea',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='gam_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='gam_description',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='voyage',
            name='geo_references',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='voyage',
            name='lat_deg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='lat_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='lat_ns',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='voyage',
            name='lat_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='location_estimated',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='voyage',
            name='logbook_entry',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='voyage',
            name='logbook_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='logbook_title',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='voyage',
            name='lon_deg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='lon_ew',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='voyage',
            name='lon_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='lon_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='running_total_oil',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='sailor_activities',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='voyage',
            name='second_mate_note',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='voyage',
            name='spotted_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='spotted_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='spotted_species',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='voyage',
            name='struck_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='struck_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='struck_species',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='voyage',
            name='vessels_sighted_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='weather_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='weather_conditions',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
