# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0002_auto_20180222_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='sailor_activities',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
