# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0008_auto_20180223_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='logbook_title',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
