# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-23 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0016_auto_20180312_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voyage',
            old_name='vessels_sighted_quantity',
            new_name='vessels_sighted',
        ),
    ]
