# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-23 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0017_auto_20180323_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='vessels_sighted',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
