# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-25 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0018_auto_20180323_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='barrels_sperm_breakdown',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
