# Generated by Django 2.0.7 on 2018-08-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapdata', '0019_auto_20180325_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='spotted_quantity',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='struck_quantity',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
