# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-26 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_geomap_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='geomap',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geomap',
            name='voyageid',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
