# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20180226_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparevoyage',
            name='label',
            field=models.CharField(max_length=32, unique=True, verbose_name='nickname for this map'),
        ),
        migrations.AlterField(
            model_name='comparevoyage',
            name='voyage_id',
            field=models.IntegerField(default=0, help_text='look for number in admin edit link for map in question', verbose_name='map ID'),
        ),
    ]
