# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20180228_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparevoyage',
            old_name='voyage_id',
            new_name='compare_geomap_id',
        ),
    ]
