# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_auto_20180228_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparevoyage',
            name='compare_voyage_id',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
